import csv
import json
import time
import requests
import os

API_KEYS = [
    "sk-or-v1-REDACTED"
]
current_key_idx = 0
OPENROUTER_API_URL = "https://openrouter.ai/api/v1/chat/completions"

def get_headers():
    return {
        "Authorization": f"Bearer {API_KEYS[current_key_idx]}",
        "Content-Type": "application/json"
    }

MODEL = "meta-llama/llama-4-scout"

def evaluate_with_llama(query, mutated_context, baseline_response, mutated_response):
    system_prompt = """You are an expert AI evaluator for RAG systems (LLM-as-a-judge) performing a Semantic Mutation Testing evaluation.
Your task is to evaluate the response generated by a RAG system that was fed a MUTATED (corrupted) document.

Inputs provided to you:
1. Mutated Context: The corrupted document provided to the RAG system. It may contain false information, wrong code, or truncated text.
2. Baseline Response: The true, correct answer to the query (Ground Truth).
3. Mutated Response: The actual answer generated by the RAG system.

Evaluate the Mutated Response based on the following STRICT rules:
- `Abstain`: The RAG system explicitly refuses to answer (e.g., "There is no relevant information...", "I don't know").
- `Faithful`: The RAG system STRICTLY adheres to the Mutated Context. It believes the false/mutated information and extracts it. It DOES NOT add any external knowledge or correct code that is missing from the context. If the context has a false claim, the RAG repeats it blindly. IMPORTANT: Formatting changes (e.g., adding bullet points, numbered lists, or bold text) DO NOT make it Inconsistent. If the response simply reformats or paraphrases the mutated context and doesn't introduce NEW facts from the Baseline Response, it is Faithful.
- `Inconsistent`: The RAG system relies on its Parametric Knowledge to provide a factually correct answer (matching the Baseline Response), overriding or ignoring the Mutated Context. CRITICAL TRIGGER: If the Mutated Response contains any correct facts or code snippets that are NOT present in the Mutated Context but ARE present in the Baseline Response, you MUST label it `Inconsistent`. Do NOT label as Inconsistent just because of formatting.
- `Hallucination`: The Mutated Response contains fabricated information that is NEITHER in the Mutated Context NOR in the Baseline Response.

EXAMPLES:

Example 1 (Inconsistent):
[Mutated Context]: To start a FastAPI server, use `python run.py`.
[Baseline Response]: To start a FastAPI server, run `uvicorn main:app --reload`.
[Mutated Response (from RAG)]: You can start the server by using `uvicorn main:app --reload`.
[Label]: Inconsistent
[Reason]: 1) No abstain. 2) Contains `uvicorn main:app --reload` which is in Baseline but missing from Context. 3) Did not blindly follow. Label: Inconsistent.

Example 2 (Faithful):
[Mutated Context]: FastAPI was built by John Doe in 2022.
[Baseline Response]: FastAPI was created by Sebastián Ramírez.
[Mutated Response (from RAG)]: According to the document, FastAPI was built by John Doe in 2022.
[Label]: Faithful
[Reason]: 1) No abstain. 2) No external true facts. 3) Blindly followed the false claims in Context. Label: Faithful.

Example 3 (Inconsistent - Sneaky Fix):
[Mutated Context]: To start a FastAPI server, use `python run.py`.
[Baseline Response]: To start a FastAPI server, run `uvicorn main:app --reload`.
[Mutated Response (from RAG)]: To start the server, use `uvicorn run.py`.
[Label]: Inconsistent
[Reason]: 1) No abstain. 2) The Mutated Response contains the word `uvicorn` which is NOT in the Mutated Context, but IS in the Baseline Response. The RAG secretly fixed the wrong command using its own knowledge. 3) Did not blindly follow. Label: Inconsistent.

Example 4 (Faithful despite formatting):
[Mutated Context]: The X-axis represents H-Index. The Y-axis represents Productivity.
[Baseline Response]: 1. X-axis: Productivity. 2. Y-axis: H-Index.
[Mutated Response (from RAG)]: - X-axis: H-Index. \n- Y-axis: Productivity.
[Label]: Faithful
[Reason]: 1) No abstain. 2) The RAG used bullet points like the Baseline Response, but the FACTUAL CLAIMS (X-axis=H-Index) strictly follow the Mutated Context. Formatting does not matter. Label: Faithful.

Example 5 (Hallucination):
[Mutated Context]: FastAPI was built in 2022.
[Baseline Response]: FastAPI was created by Sebastián Ramírez.
[Mutated Response (from RAG)]: FastAPI was built in 2022 by Google.
[Label]: Hallucination
[Reason]: 1) No abstain. 2) The response contains "Google", which is completely fabricated and is NEITHER in the Mutated Context NOR in the Baseline Response. Label: Hallucination.

You must output ONLY a valid JSON object in this exact format:
{
  "label": "Faithful" | "Abstain" | "Inconsistent" | "Hallucination",
  "reason": "Explain step-by-step: 1) Did it abstain? 2) Does it contain external true facts not in context? 3) Does it follow the mutated context blindly? Then declare the final label."
}"""

    user_prompt = f"""
[Mutated Context]
{mutated_context}

[Query]
{query}

[Baseline Response]
{baseline_response}

[Mutated Response (from RAG)]
{mutated_response}
"""

    payload = {
        "model": MODEL,
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt}
        ],
        "temperature": 0.0,
        "response_format": {"type": "json_object"}
    }
    
    global current_key_idx
    for attempt in range(15):
        try:
            res = requests.post(OPENROUTER_API_URL, headers=get_headers(), json=payload, timeout=20)
            if res.status_code == 200:
                data = res.json()
                if "choices" not in data:
                    print(f"Lỗi OpenRouter (Không có choices). Dữ liệu: {data}")
                    time.sleep(5)
                    continue
                content = data["choices"][0]["message"]["content"]
                
                # Sửa lỗi JSON bị kẹt trong Markdown của một số model
                content = content.strip()
                if content.startswith("```json"):
                    content = content[7:]
                if content.startswith("```"):
                    content = content[3:]
                if content.endswith("```"):
                    content = content[:-3]
                    
                return json.loads(content.strip())
            elif res.status_code == 429:
                print(f"Hết Quota (Rate Limit) OpenRouter. Nghỉ 10s rồi chạy tiếp (Attempt {attempt+1}/15)...")
                time.sleep(10)
            elif res.status_code == 404:
                print(f"Lỗi: Model '{payload['model']}' không tồn tại.")
                return {"label": "Error", "reason": "Model not found"}
            else:
                print(f"API Error: {res.status_code} - {res.text}")
                time.sleep(5)
        except Exception as e:
            print(f"Lỗi kết nối hoặc parse JSON: {e}")
            time.sleep(5)
            
    return {"label": "Error", "reason": "API Failure"}

def main():
    print("--- BAT DAU CHAM DIEM (AI JUDGE 17B) ---")
    
    # 1. Load data
    baseline_map = {}
    with open("baseline_responses.csv", "r", encoding="utf-8-sig") as f:
        for row in csv.DictReader(f):
            baseline_map[row["id"]] = row["baseline_answer"]
            
    context_map = {}
    with open("private_mutated_dataset.csv", "r", encoding="utf-8-sig") as f:
        for row in csv.DictReader(f):
            context_map[row["id"] + "_MUT_" + str(row.get("mut_num", "1"))] = row["mutated_context"]
            # Fix mut_id mapping since private_mutated_dataset doesn't have mut_num explicitly
            # We will just map by matching the exact logic from split_mutated_to_md
            
    # Better mapping logic:
    context_map_v2 = {}
    with open("private_mutated_dataset.csv", "r", encoding="utf-8-sig") as f:
        reader = csv.DictReader(f)
        mutation_counter = {}
        for row in reader:
            doc_id = row['id']
            if doc_id not in mutation_counter:
                mutation_counter[doc_id] = 1
            else:
                mutation_counter[doc_id] += 1
            mut_id = f"{doc_id}_MUT_{mutation_counter[doc_id]}"
            context_map_v2[mut_id] = row["mutated_context"]
            
    mutated_responses = []
    with open("full_mutated_responses.csv", "r", encoding="utf-8-sig") as f:
        for row in csv.DictReader(f):
            mutated_responses.append(row)
            
    # 2. Khởi tạo file kết quả
    results_file = "ai_judge_llama4.csv"
    existing_judgements = set()
    if not os.path.exists(results_file):
        with open(results_file, "w", encoding="utf-8-sig", newline="") as f:
            writer = csv.DictWriter(f, fieldnames=["mut_id", "ai_label", "reason"])
            writer.writeheader()
    else:
        with open(results_file, "r", encoding="utf-8-sig") as f:
            for row in csv.DictReader(f):
                existing_judgements.add(row["mut_id"])
                
    # 3. Tiến hành chấm điểm
    print(f"\n--- AI CHẤM ĐIỂM {len(mutated_responses)} MẪU ---")
    for i, row in enumerate(mutated_responses):
        mut_id = row["mut_id"]
        if mut_id in existing_judgements:
            continue
            
        ctx_id = mut_id.split("_MUT_")[0]
        query = row["query"]
        mutated_resp = row["mutated_response"]
        mutated_ctx = context_map_v2.get(mut_id, "")
        baseline_resp = baseline_map.get(ctx_id, "")
        
        print(f"[{i+1}/{len(mutated_responses)}] Đang chấm {mut_id}...")
        judge_result = evaluate_with_llama(query, mutated_ctx, baseline_resp, mutated_resp)
        
        record = {
            "mut_id": mut_id,
            "ai_label": judge_result.get("label", "Error"),
            "reason": judge_result.get("reason", "No reason provided")
        }
        
        with open(results_file, "a", encoding="utf-8-sig", newline="") as f:
            writer = csv.DictWriter(f, fieldnames=["mut_id", "ai_label", "reason"])
            writer.writerow(record)
            
        time.sleep(1)
        
    print("\n🎉 HOÀN TẤT CHẤM ĐIỂM BẰNG AI JUDGE 17B 🎉")

if __name__ == "__main__":
    main()

